name: Build LaTeX document
on: [push, workflow_dispatch]
jobs:
  book-with-pictures:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: download fonts
        run: |
          wget  --output-document FZSONG-ZhongHuaSongPlane00.TTF https://github.com/xiangrongjingujiu/ZhongHuaSongFont/raw/master/%E4%B8%AD%E5%8D%8E%E4%B9%A6%E5%B1%80%E5%AE%8B%E4%BD%93%E5%AD%97%E5%BA%93/FZSONG_ZhongHuaSongPlane00_2021051420210514150927.TTF
          wget --output-document FZSONG-ZhongHuaSongPlane02.TTF https://github.com/xiangrongjingujiu/ZhongHuaSongFont/raw/master/%E4%B8%AD%E5%8D%8E%E4%B9%A6%E5%B1%80%E5%AE%8B%E4%BD%93%E5%AD%97%E5%BA%93/FZSONG_ZhongHuaSongPlane02_2021012120210122112919.TTF
          wget https://github.com/xiangrongjingujiu/FangZhengChaoDaZiFuJi/raw/master/%E6%96%B9%E6%AD%A3%E6%A5%B7%E4%BD%93%E8%B6%85%E5%A4%A7%E5%AD%97%E7%AC%A6%E9%9B%86/FZJCGFKTK.TTF
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: compile failed, get help by ssh
        # use tmate to ssh to remote running instance
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
      - name: copy out pdf
        uses: actions/upload-artifact@v1
        with:
          # the filename in workflow tab
          name: book-with-pictures
          # main.tex generates main.pdf
          # copy this file to workflow tab
          path: main.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        # only release with git-tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  book-with-compressed-pictures:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: download fonts
        run: |
          wget  --output-document FZSONG-ZhongHuaSongPlane00.TTF https://github.com/xiangrongjingujiu/ZhongHuaSongFont/raw/master/%E4%B8%AD%E5%8D%8E%E4%B9%A6%E5%B1%80%E5%AE%8B%E4%BD%93%E5%AD%97%E5%BA%93/FZSONG_ZhongHuaSongPlane00_2021051420210514150927.TTF
          wget --output-document FZSONG-ZhongHuaSongPlane02.TTF https://github.com/xiangrongjingujiu/ZhongHuaSongFont/raw/master/%E4%B8%AD%E5%8D%8E%E4%B9%A6%E5%B1%80%E5%AE%8B%E4%BD%93%E5%AD%97%E5%BA%93/FZSONG_ZhongHuaSongPlane02_2021012120210122112919.TTF
          wget https://github.com/xiangrongjingujiu/FangZhengChaoDaZiFuJi/raw/master/%E6%96%B9%E6%AD%A3%E6%A5%B7%E4%BD%93%E8%B6%85%E5%A4%A7%E5%AD%97%E7%AC%A6%E9%9B%86/FZJCGFKTK.TTF
      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          jpegQuality: "10"
          pngQuality: "10"
          webpQuality: "10"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: compile failed, get help by ssh
        # use tmate to ssh to remote running instance
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
      - name: copy out pdf
        uses: actions/upload-artifact@v1
        with:
          # the filename in workflow tab
          name: book-with-compressed-pictures
          # main.tex generates main.pdf
          # copy this file to workflow tab
          path: main.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        # only release with git-tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  book-without-pictures:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: download fonts
        run: |
          wget  --output-document FZSONG-ZhongHuaSongPlane00.TTF https://github.com/xiangrongjingujiu/ZhongHuaSongFont/raw/master/%E4%B8%AD%E5%8D%8E%E4%B9%A6%E5%B1%80%E5%AE%8B%E4%BD%93%E5%AD%97%E5%BA%93/FZSONG_ZhongHuaSongPlane00_2021051420210514150927.TTF
          wget --output-document FZSONG-ZhongHuaSongPlane02.TTF https://github.com/xiangrongjingujiu/ZhongHuaSongFont/raw/master/%E4%B8%AD%E5%8D%8E%E4%B9%A6%E5%B1%80%E5%AE%8B%E4%BD%93%E5%AD%97%E5%BA%93/FZSONG_ZhongHuaSongPlane02_2021012120210122112919.TTF
          wget https://github.com/xiangrongjingujiu/FangZhengChaoDaZiFuJi/raw/master/%E6%96%B9%E6%AD%A3%E6%A5%B7%E4%BD%93%E8%B6%85%E5%A4%A7%E5%AD%97%E7%AC%A6%E9%9B%86/FZJCGFKTK.TTF
      - name: compile with `draft` option
        run: |
          sed -i 's/^\\usepackage{graphicx}$/\\usepackage[draft]{graphicx}/' main.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: compile failed, get help by ssh
        # use tmate to ssh to remote running instance
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
      - name: copy out pdf
        uses: actions/upload-artifact@v1
        with:
          # the filename in workflow tab
          name: book-without-pictures
          # main.tex generates main.pdf
          # copy this file to workflow tab
          path: main.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        # only release with git-tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
